### ISSUE TITLE
Write the routes dict instead of the routes list

### ISSUE THREAD

**Issue by arneboockmeyer** [simulate-digital-rail/railway-route-generator#21]
When https://github.com/simulate-digital-rail/yaramo/pull/26 is merged, routes in topology are stored in a dict instead of a list. This needs to be changed here as well.

**Comment by jeriox** [comment]
closed by https://github.com/simulate-digital-rail/railway-route-generator/commit/a0cb8d2f5437a8305085425a628cda32955b3d08
