### ISSUE TITLE
Routes for signals in wrong direction are generated

### ISSUE THREAD

**Issue by jeriox** [simulate-digital-rail/railway-route-generator#5]
When creating routes for the example of Potsdam Hbf, one is presented with 8 routes from any given entry signal, one for each exit signal present in the station. This is incorrect, as a route can only be set to a signal in the direction of travel of the train. Unfortunately, this is hard to derive from the data, as tracks do not have an orientation inside of stations and therefor one cannot distinguish the direction. Even if the signals have set a direction (as is the case for Potsdam Hbf in ORM), there is an actual route from the forward entry signal to an exit signal on the tracks that continue to be the backward direction after the station. (Example: coming from the east, there is a route to the N143 signal which belongs to the track that becomes the backward track after the station).

![grafik](https://user-images.githubusercontent.com/12702135/202427484-aa6a6315-29d7-4840-a6f2-f1d118e355bf.png)

**Comment by arneboockmeyer** [comment]
@jeriox Please check if this is still a problem after https://github.com/arneboockmeyer/railway-route-generator/pull/7

**Comment by jeriox** [comment]
closed by #7
